services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: signupdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: signupdb
      DB_USER: postgres
      DB_PASSWORD: postgres

volumes:
  pgdata:
