services:
  backend:
    build: .
    ports:
      - "5000:50000"
    env_file:
      - backend/.env
    depends_on:
      - db
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: signubdb
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: