name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin

      - name: Run Trivy scan (filesystem + secrets + config, HIGH & CRITICAL only)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'json'
          output: 'results/result.json'
          severity: 'HIGH,CRITICAL'
          scanners: 'vuln,secret,config'
          
      - name: Upload Trivy artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: results/result.json

  push-artifact-to-branch:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: trivy-report
          path: security-report-result

      - name: Configure Git
        run: |
          git config --global user.name "Action Bot"
          git config --global user.email "action@example.com"

      - name: Push report to logs branch
        run: |
          git fetch origin
          git switch logs || git switch --create logs
          mkdir -p reports
          cp security-report-result/result.json reports/trivy-scan-$(date +'%Y-%m-%d-%H-%M-%S').json
          git add reports/
          git commit -m "Add Trivy report from $(date)"
          git push origin logs
